spring:
  config:
    activate:
      on-profile: dev
    import:
      - optional:file:./.env[.properties]
      - optional:file:./mopl-api/.env[.properties]
  datasource:
    url: ${MOPL_DB_URL:jdbc:mysql://localhost:3306/mopl?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${MOPL_DB_USERNAME:app}
    password: ${MOPL_DB_PASSWORD:app}
  jpa:
    hibernate:
      ddl-auto: ${MOPL_DDL_AUTO:update}
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  data:
    redis:
      host: ${MOPL_REDIS_HOST:localhost}
      port: ${MOPL_REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${MOPL_KAFKA_BOOTSTRAP:localhost:9092}

server:
  port: ${MOPL_PORT:8080}

logging:
  level:
    org.hibernate.SQL: ${MOPL_SQL_LOG_LEVEL:debug}
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: off

jwt:
  secret: ${JWT_SECRET:dev-secret-key-must-be-at-least-32-characters-long-for-hs256-algorithm}
  access-token-validity-in-seconds: ${JWT_VALIDITY:86400} # 디폴트 24시간
  refresh-token-validity-in-seconds: ${JWT_REFRESH_VALIDITY:604800} # 디폴트 7일
